version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: whomaun
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: food_ai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://whomaun:mysecretpassword@db:5432/food_ai_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

volumes:
  pgdata:
