"""Initial

Revision ID: 5342c52faba7
Revises: 
Create Date: 2026-04-02 02:29:31.462942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5342c52faba7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activitylevel'), nullable=False),
    sa.Column('goal', sa.Enum('loss', 'gain', 'maintain', name='goal'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('correction_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('correct_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='reportstatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_reports_id'), 'correction_reports', ['id'], unique=False)
    op.drop_index('ix_corrections_id', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.add_column('products', sa.Column('barcode', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('composition', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_index('ix_products_name', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    op.create_unique_constraint(None, 'products', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('ix_products_name', 'products', ['name'], unique=True)
    op.drop_column('products', 'is_verified')
    op.drop_column('products', 'composition')
    op.drop_column('products', 'barcode')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('predicted_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('corrected_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='corrections_pkey')
    )
    op.create_index('ix_corrections_id', 'corrections', ['id'], unique=False)
    op.drop_index(op.f('ix_correction_reports_id'), table_name='correction_reports')
    op.drop_table('correction_reports')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
